//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServicesTest.MensajeWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MensajeWS.Imensajes")]
    public interface Imensajes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imensajes/saludar", ReplyAction="http://tempuri.org/Imensajes/saludarResponse")]
        string saludar(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imensajes/despedir", ReplyAction="http://tempuri.org/Imensajes/despedirResponse")]
        string despedir(string name, string curso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImensajesChannel : SOAPServicesTest.MensajeWS.Imensajes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImensajesClient : System.ServiceModel.ClientBase<SOAPServicesTest.MensajeWS.Imensajes>, SOAPServicesTest.MensajeWS.Imensajes {
        
        public ImensajesClient() {
        }
        
        public ImensajesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImensajesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImensajesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImensajesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string saludar(string name) {
            return base.Channel.saludar(name);
        }
        
        public string despedir(string name, string curso) {
            return base.Channel.despedir(name, curso);
        }
    }
}
